### PR TITLE
[WIP] GHC8 Compatibility

### PR DESCRIPTION
**Pull request by acowley**
(At least) two open issues I need help with:
- Bounds for the `transformers` dependency
- `libc++` vs `libstdc++`. I needed to use `libc++` when building with nix-supplied tooling as the `libstdc++` in `nixpkgs` for `darwin` is too old (iiuc). When I built with `stack` by itself (no nix) on an up-to-date OS X machine, `libstdc++` was fine. Perhaps there is a nice way to override this choice of library and we can just make a note of how to do so.

### CODE REVIEW

**Comment by cocreature** [comment]
First of all it looks like I wasn’t clear on which branch is the most up2date, `metadata-3.8` is newer than this branch so it would be great if you could make this PR again against this branch. Sorry for that, I should really clean my branches up.

> Bounds for the transformers dependency

I guess I would test 0.4 and 0.5 and set it to >= 0.4 and < 0.6. 0.3 is ancient but I still see 0.4 reasonably often.

> libc++ vs libstdc++.

The proper solution to this is calling `llvm-config` to figure out how clang was build. In fact Benjamin has already implemented this and it is also on the `metadata-3.8` branch https://github.com/cocreature/llvm-general/commit/045a1a1c6d3f5c0d3bae138b5648e16ec04698b5
There is a problem here since simply using all flags is also incorrect, but at least the decision of using `libc++` or `libstdc++` should work.

**Comment by cocreature** [comment]
> First of all it looks like I wasn’t clear on which branch is the most up2date, metadata-3.8 is newer than this branch so it would be great if you could make this PR again against this branch. Sorry for that, I should really clean my branches up.

Nvm that is a bad idea since I still have a PR open from that branch. I’ll just merge metadata-3.8 into this branch.

**Comment by cocreature** [comment]
I’m really sorry but I had to force push to the branch to make the history consistent with `metadata-3.8` which has screwed up your pr completely.

I suppose you probably need to cherry pick the commits. If that’s too much work for you I can also just pick the commits myself.

I guess that’s the lession I needed for not having messed up public branches.

**Comment by acowley** [comment]
I sorted out the patches onto your `llvm-3.8` branch and hopefully sorted out the build setup. It now picks up the proper stdlib.

**Comment by cocreature** [comment]
There are two minor issues (we actually need some of the cxxflags in ccflags, e.g. rtti) but I’ll go over these myself later today, thanks for your help!

**Pull request merged**
